### ISSUE TITLE
add support for Windows-1252 fallback

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/encoding_rs_io#3]
We want to expose the ability to "use Windows-1252, but if there's a BOM, honor the BOM." See @hsivonen's comment here: https://github.com/hsivonen/encoding_rs/issues/8#issuecomment-411356371

I'm not sure if this is something where we can add a new option to the builder for, or if this requires deeper changes in the decoder.

**Comment by Ten0** [comment]
One way to get this could be to integrate with `https://docs.rs/chardetng/0.1.17/chardetng/struct.EncodingDetector.html`, which is by the author of `encoding_rs_io`. We have use-cases for charset auto-detection now too, so that would be helpful :)

**Comment by dralley** [comment]
I believe the `bom_override` option satisfies this?

>When this is enabled, and if a BOM is found, then the encoding indicated by that BOM is used even if an explicit encoding has been set via the encoding method.

**Comment by Ten0** [comment]
We don't have a bom

**Comment by BurntSushi** [comment]
> I believe the `bom_override` option satisfies this?

Yup I believe so.

@Ten0 This issue is more narrowly scoped then perhaps what you're thinking? I would suggest you file a new issue with a detailed description of the problem you're trying to solve.
